name: TurboBoostSwitcher
options:
  bundleIdPrefix: com.bestwaverock
targets:
  TurboBoostSwitcher:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: App/Sources
      - path: Shared
    settings:
      INFOPLIST_KEY_LSUIElement: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.bestwaverock.TurboBoostSwitcher
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
  TurboBoostDaemon:
    type: command-line-tool
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Daemon/Sources
      - path: Shared
